### PR TITLE
GitHub actions for Continuous Integration

### LINKED ISSUE #1628: [2h📦] Switch to GitHub Actions
https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

### PR DESCRIPTION
**Pull request by chigby**
Fixes #1628

### CODE REVIEW

**Comment by chigby** [comment]
This seems to be working now, but I can't figure out why the Travis checks are still showing up as "Waiting..." after I've removed the `.travis.yml` file.

Is this something we have to remove on the Travis site (or GitHub) itself?

**Review by nmorduch — CHANGES_REQUESTED** [review]
Let's keep Travis around simultaneously for a bit, since I think that will allow the best testing. We want to see what this is like when the tests fail, too.

**Comment by nmorduch** [comment]
We just discussed having it be that this is split into two PRs: one for adding GitHub actions, and one for removing Travis (which we'll wait to merge)

**Comment by chigby** [comment]
Removed the travis changes from this PR

**Review by nmorduch — CHANGES_REQUESTED** [review]
You gotta change Travis to look at settings/ci.py now!

**Review by nmorduch — APPROVED** [review]
Thank you :)

**Pull request merged**
