### PR TITLE
Person model changes 3

### LINKED ISSUE #306: Our People classification
Per Mark's feedback, we don't need a distinction between national and program fellows. So we can just have 'Fellow' listed in the role dropdown

### PR DESCRIPTION
**Pull request by sanajaved7**
- Combines roles for New America Fellow and Program Fellow to just "Fellow"

[Resolves #306]

### CODE REVIEW

**Comment by georgiamoon** [comment]
Oop -- late to the game here, but I thought that we weren't combining program fellow and new america fellow? or are we clarifying the designation differently?

**Comment by sanajaved7** [comment]
Hey @georgiamoon - I believe this was the result of a discussion between @rossvanderlinde and Mark. My understanding from @rossvanderlinde is that the distinction between program and NA fellows can be blurred and since we can associate people with programs we didn't need a separate role for program fellow. Is that correct @rossvanderlinde?

**Comment by rossvanderlinde** [comment]
@georgiamoon AMS asked me to ask MS for a decision. I can explain further in person if necessary

**Comment by georgiamoon** [comment]
OK -- just checking that there's still a way to designate, as that designation matters to people in other contexts.

**Comment by kjacks** [comment]
:+1:

**Pull request merged**
