### PR TITLE
Tests and refactoring of new events setup

### LINKED ISSUE #837: Review Events page setup
Multiple people have said they think past events are jumbled / not ordered. Actually they're ordered but start from exactly a year ago, which is too confusing.

One solution may be ordering past events (newest to oldest) differently from future events (oldest to newest). If someone selects dates that crossover both, then it can be ordered newest to oldest too.

A summer intern task could be assembling case studies of how other orgs handle events pages with past and future work. Should involve events team and Tyler B who flagged this issue

### PR DESCRIPTION
**Pull request by sanajaved7**
This is looking good @kjacks! I really like your implementation here. I added the following things:
- Tests for new functionality
- Moved event specific logic under event/models.py
- Fixed merge conflicts

Resolves #837 #863

### CODE REVIEW

**Comment by kjacks** [comment]
Looks good to merge 👍

**Comment by sanajaved7** [comment]
Thanks @kjacks and before we merge, would you mind adding issues for the remaining tests to write for this feature?

**Comment by sanajaved7** [comment]
@kjacks I went ahead and added the test for event ordering. Will merge now.

**Comment by kjacks** [comment]
Great! Thank you so much for doing that

**Pull request merged**
