### PR TITLE
Set Experts Page to Our People

### LINKED ISSUE #668: Set Experts Page to Our People

### PR DESCRIPTION
**Pull request by kjacks**
- set header links to our people instead of experts page
- removed experts from about sidemenu

Resolves #668

### CODE REVIEW

**Comment by kjacks** [comment]
@sanajaved7 We should talk about this briefly.  Ross and I were talking about the experts page and he thought that without the ability to search by expertise area, the experts page was exactly the same as the our people page, so therefore for now we should just have the our people page.  The header experts links would now just go to the our people page

**Comment by kjacks** [comment]
I left the experts model and template in there because it is something that we will hopefully build out soon and won't want to have to crazily change structure, but let's definitely touch base on this

**Comment by sanajaved7** [comment]
@kjacks that sounds like a good plan to me while we figure out how we'd like to build out that page 👍

**Comment by kjacks** [comment]
@sanajaved7 great!

**Pull request merged**
