### PR TITLE
update eleastic search version

### PR DESCRIPTION
**Pull request by genuineBuildMonkey**
update to elastic search 6+

### CODE REVIEW

**Comment by lorenries** [comment]
Thanks Paul,

[Looking at the Wagtail docs](http://docs.wagtail.io/en/v2.3/topics/search/backends.html#elasticsearch-backend), if we bump to elastic search 6+, we need to use 6.3.0 or earlier, and also update the Wagtail settings [here](https://github.com/newamericafoundation/newamerica-cms/blob/c1e10a42fc7d6a42eb08d75acd38db55de418376/newamericadotorg/settings/production.py#L62).

**Comment by genuineBuildMonkey** [comment]
It looks like the extra keys in settings are optional?


> WAGTAILSEARCH_BACKENDS = {
>     'default': {
>         'BACKEND': 'wagtail.search.backends.elasticsearch2',
>         'URLS': ['http://localhost:9200'],
>         'INDEX': 'wagtail',
>         'TIMEOUT': 5,
>         'OPTIONS': {},
>         'INDEX_SETTINGS': {},
>     }
> }
> 
> Other than BACKEND, the keys are optional and default to the values shown.

..Which is not to say we won't have to tweak a setting somewhere.

Can we try 6.3.0 and see what it does?

**Comment by genuineBuildMonkey** [comment]
Thanks. Didn't get the relevance of the 2.

**Comment by lorenries** [comment]
yeah but I think we also have to change `BACKEND` to `wagtail.search.backends.elasticsearch6`, everything else is optional. Ok, merging, 🤞.

**Pull request merged**
