### PR TITLE
Feature to filter content by program, initiative, or date on content homepages

### LINKED ISSUE #620: Build out content homepage filter functions
- Filter by program
- Filter by date
- Filter by initiative when inside program

### PR DESCRIPTION
**Pull request by sanajaved7**
Allows filtering of content by date, program, or initiative on:
- Program content homepages (not events)
- Program event homepages
- Org wide content homepages (not events)
- Org wide event homepage

Also refactors the get context function for all org wide content homepages

[Resolves #620]

### CODE REVIEW

**Comment by kjacks** [comment]
@sanajaved7 This branch is built on top of the other one right - I'm just making sure because of the overlapping commits that there are no conflicts?

**Comment by sanajaved7** [comment]
@kjacks yep! once that one is merged this should catch up - it's just I could only get the server to run in the branch with the fixed migrations so I had to branch this one off of that.

**Comment by kjacks** [comment]
absolutely, I'll wait to review this one til the other is merged

**Comment by sanajaved7** [comment]
@kjacks should be good to review now!

**Comment by kjacks** [comment]
Looks great!

**Pull request merged**
