### PR TITLE
Add EXTRA_STATIC_URL

### PR DESCRIPTION
**Pull request by kaedroho**
`STATIC_URL` will now point at Django-managed static, but we are going to leave fonts, logos, social images, etc in the S3 bucket. So I've added `EXTRA_STATIC_URL` which will point at the S3 bucket until we find a new place for these files.

To deploy:

 - Set `EXTRA_STATIC_URL` to the same value as `STATIC_URL` (must be done before deployment as this value is read during the build stage)
 - Deploy this branch
 - Remove `STATIC_BUCKET_NAME` and `STATIC_URL`

### CODE REVIEW

**Comment by nmorduch** [comment]
So this is the #1511 plus one commit, yeah? So it supersedes that pr?

**Comment by kaedroho** [comment]
We need that PR as it updates Whitenoise. It's based on it but doesn't supersede it, we should merge the Wagtail update first then this.

**Comment by nmorduch** [comment]
What I want to do is set the value of `EXTRA_STATIC_URL` as what `STATIC_URL` currently is on production, for all three servers, right?

**Comment by kaedroho** [comment]
> What I want to do is set the value of EXTRA_STATIC_URL as what STATIC_URL currently is on production, for all three servers, right?

Yep, that should work!

**Comment by nmorduch** [comment]
If you look on the dev server, it's currently looking for images at STATIC_URL when it needs to be at that plus /static

**Comment by nmorduch** [comment]
And then it works fine when I changed EXTRA_STATIC_URL to account for that, but it would probably be better to add `/static` in the code

**Pull request merged**
